/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
     ResultSet r;
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1reg = new javax.swing.JLabel();
        juserid = new javax.swing.JLabel();
        jTextuserid = new javax.swing.JTextField();
        jTextusername = new javax.swing.JTextField();
        jusername = new javax.swing.JLabel();
        jphone = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        juserpass = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextphone = new javax.swing.JTextField();
        jTextemail = new javax.swing.JTextField();
        jTextuserpass = new javax.swing.JTextField();
        jComrole = new javax.swing.JComboBox<>();
        jButtonredistration = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jButtonlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel6.setText("Library management System");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 108, 297, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/daniel-zjV8ptYgcEo-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 330, 320));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1reg.setFont(new java.awt.Font("Segoe UI Light", 1, 22)); // NOI18N
        jLabel1reg.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1reg.setText("Registration");
        jPanel2.add(jLabel1reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        juserid.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        juserid.setForeground(new java.awt.Color(51, 255, 255));
        juserid.setText("user_id");
        jPanel2.add(juserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jTextuserid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 255)));
        jPanel2.add(jTextuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        jTextusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 255)));
        jPanel2.add(jTextusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 180, -1));

        jusername.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jusername.setForeground(new java.awt.Color(51, 255, 255));
        jusername.setText("user_name");
        jPanel2.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jphone.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jphone.setForeground(new java.awt.Color(51, 255, 255));
        jphone.setText("Phone");
        jPanel2.add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jemail.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jemail.setForeground(new java.awt.Color(51, 255, 255));
        jemail.setText("Email");
        jPanel2.add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        juserpass.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        juserpass.setForeground(new java.awt.Color(51, 255, 255));
        juserpass.setText("User_password");
        jPanel2.add(juserpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Role");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jTextphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 255)));
        jPanel2.add(jTextphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, -1));

        jTextemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 255)));
        jTextemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextemailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, -1));

        jTextuserpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 255, 255)));
        jPanel2.add(jTextuserpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 180, -1));

        jComrole.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jComrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Instructor", "Student", "Teacher" }));
        jComrole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        jPanel2.add(jComrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jButtonredistration.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButtonredistration.setForeground(new java.awt.Color(0, 204, 204));
        jButtonredistration.setText("Registration");
        jButtonredistration.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonredistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonredistrationActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonredistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jButtoncancel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButtoncancel.setForeground(new java.awt.Color(0, 204, 204));
        jButtoncancel.setText("Cancel");
        jButtoncancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtoncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 80, -1));

        jButtonlogin.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButtonlogin.setForeground(new java.awt.Color(0, 204, 204));
        jButtonlogin.setText("login");
        jButtonlogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/user-16.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/student-16.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/phone-42-16.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/gmail-login-16.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/lock-7-16.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextemailActionPerformed

    private void jButtonredistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonredistrationActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Library_Management","root","");
            String sql="INSERT INTO `user_registration` VALUES (?,?,?,?,?,?)";
            PreparedStatement ptst = conn.prepareStatement(sql);
            ptst.setString(1,jTextuserid.getText() );
            ptst.setString(2,jTextusername.getText() );
            ptst.setString(3,jTextphone.getText() );
            ptst.setString(4,jTextemail.getText() );
            ptst.setString(5,jTextuserpass.getText() );
            ptst.setString(6,jComrole.getSelectedItem().toString() );
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this," registersuccessfull ");
            conn.close();

        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonredistrationActionPerformed

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
        // TODO add your handling code here:
       new Login().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JButton jButtonredistration;
    private javax.swing.JComboBox<String> jComrole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1reg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextemail;
    private javax.swing.JTextField jTextphone;
    private javax.swing.JTextField jTextuserid;
    private javax.swing.JTextField jTextusername;
    private javax.swing.JTextField jTextuserpass;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jphone;
    private javax.swing.JLabel juserid;
    private javax.swing.JLabel jusername;
    private javax.swing.JLabel juserpass;
    // End of variables declaration//GEN-END:variables
}
